services: 
  db:
    image: 'postgres:16' 
    environment:
      - POSTGRES_PASSWORD=lot230510
      - POSTGRES_USER=max
      - POSTGRES_DB=shelter
    volumes:
      - db_data:/var/lib/postgresq1/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  etl:
    build: .
    command: https://shelterdata.s3.amazonaws.com/shelter1000.csv
    depends_on:
      - db

volumes:
  db_data: